# Generated by Django 5.2.11 on 2026-03-30 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_name", models.CharField(max_length=50)),
                ("projected_quantity", models.PositiveSmallIntegerField()),
                ("actual_quantity", models.PositiveSmallIntegerField()),
                ("needed_by", models.CharField(max_length=50)),
                ("unit_of_measure", models.CharField(max_length=23)),
            ],
        ),
        migrations.CreateModel(
            name="ConstructionProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="project_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="project_manager",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConstructionSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("site_opening_date", models.DateField()),
                (
                    "contruction_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.constructionproject",
                    ),
                ),
                (
                    "foreman",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="site_foreman",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "storekeeper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="site_storekeeper",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(auto_now_add=True)),
                (
                    "work_description",
                    models.TextField(
                        help_text="Description of works carried out during the day"
                    ),
                ),
                (
                    "phase_start_date",
                    models.DateField(
                        help_text="When the current phase of work started"
                    ),
                ),
                (
                    "days_elapsed",
                    models.IntegerField(
                        default=0,
                        help_text="Number of days the work phase has been ongoing",
                    ),
                ),
                (
                    "expected_completion_date",
                    models.DateField(
                        help_text="When this phase of work is expected to be completed"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or observations"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "construction_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to="core.constructionsite",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Construction Report",
                "verbose_name_plural": "Daily Construction Reports",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="DailyReportMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "projected_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Projected/planned quantity for this phase",
                        max_digits=10,
                    ),
                ),
                (
                    "actual_quantity_used",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual quantity used on this day",
                        max_digits=10,
                    ),
                ),
                (
                    "unit_of_measurement",
                    models.CharField(
                        default="pcs",
                        help_text="Unit of measurement (e.g., pcs, kg, m, liters)",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "daily_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials_used",
                        to="core.dailyreport",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.material",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Report Material",
                "verbose_name_plural": "Daily Report Materials",
            },
        ),
        migrations.CreateModel(
            name="WorkItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("professional_in_charge", models.CharField(max_length=50)),
                ("proposed_start_date", models.DateField()),
                ("start_date", models.DateField()),
                ("proposed_end_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "construction_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.constructionsite",
                    ),
                ),
                ("material_needs", models.ManyToManyField(to="core.material")),
            ],
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="work_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_reports",
                to="core.workitem",
            ),
        ),
    ]
