# Generated by Django 5.2.11 on 2026-04-06 02:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyreportmaterial",
            name="daily_report",
        ),
        migrations.RemoveField(
            model_name="dailyreportmaterial",
            name="material",
        ),
        migrations.RenameField(
            model_name="constructionproject",
            old_name="owner",
            new_name="client",
        ),
        migrations.RenameField(
            model_name="constructionsite",
            old_name="contruction_project",
            new_name="construction_project",
        ),
        migrations.RemoveField(
            model_name="workitem",
            name="material_needs",
        ),
        migrations.RemoveField(
            model_name="workitem",
            name="professional_in_charge",
        ),
        migrations.AddField(
            model_name="constructionproject",
            name="actual_start_date",
            field=models.DateField(
                default=datetime.datetime(
                    2026, 4, 6, 2, 12, 19, 698532, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="constructionproject",
            name="project_description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="constructionproject",
            name="project_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="constructionproject",
            name="project_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="constructionproject",
            name="project_start_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="constructionproject",
            name="project_status",
            field=models.CharField(
                choices=[
                    ("Planned", "Planned"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                    ("On Hold", "On Hold"),
                    ("Delayed", "Delayed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Planned",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workitem",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="workitem",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="workitem",
            name="work_status",
            field=models.CharField(
                choices=[
                    ("Planned", "Planned"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                    ("On Hold", "On Hold"),
                    ("Delayed", "Delayed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Planned",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="constructionsite",
            name="site_opening_date",
            field=models.DateField(
                default=datetime.datetime(
                    2026, 4, 6, 2, 12, 19, 698965, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="material_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="material",
            name="needed_by",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="material",
            name="unit_of_measure",
            field=models.CharField(
                choices=[
                    ("Piece", "Piece"),
                    ("Kilogram", "Kilogram"),
                    ("Liter", "Liter"),
                    ("Meter", "Meter"),
                    ("Pcs", "Pcs"),
                    ("Square Meter", "Square Meter"),
                    ("Cubic Meter", "Cubic Meter"),
                    ("Bag", "Bag"),
                    ("Length", "Length"),
                    ("Roll", "Roll"),
                    ("Other", "Other"),
                ],
                max_length=23,
            ),
        ),
        migrations.AlterField(
            model_name="workitem",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workitem",
            name="proposed_end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2026, 4, 7, 2, 12, 19, 699929, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="workitem",
            name="proposed_start_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="workitem",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="JobItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_status",
                    models.CharField(
                        choices=[
                            ("Planned", "Planned"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("On Hold", "On Hold"),
                            ("Delayed", "Delayed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Planned",
                        max_length=20,
                    ),
                ),
                (
                    "job_artisan",
                    models.CharField(
                        choices=[
                            ("Mason", "Mason"),
                            ("Plumber", "Plumber"),
                            ("Electrician", "Electrician"),
                            ("Carpenter", "Carpenter"),
                            ("Painter", "Painter"),
                            ("Roofer", "Roofer"),
                            ("Iron Bender", "Iron Bender"),
                            ("Tiler", "Tiler"),
                            ("Glass Worker", "Glass Worker"),
                            ("Aluminium Worker", "Aluminium Worker"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("job_name", models.CharField(default="", max_length=50)),
                ("job_description", models.TextField(default="")),
                ("projected_start_date", models.DateField()),
                ("projected_end_date", models.DateField()),
                ("actual_start_date", models.DateField(blank=True, null=True)),
                ("actual_end_date", models.DateField(blank=True, null=True)),
                ("material_needs", models.ManyToManyField(to="core.material")),
                (
                    "work_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_items",
                        to="core.workitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_status",
                    models.CharField(
                        choices=[
                            ("Submitted", "Submitted"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Submitted",
                        max_length=20,
                    ),
                ),
                (
                    "report_date",
                    models.DateField(
                        default=datetime.datetime(
                            2026, 4, 6, 2, 12, 19, 701644, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "expected_completion_date",
                    models.DateField(
                        help_text="When this phase of work is expected to be completed"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or observations"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to="core.jobitem",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Job Report",
                "verbose_name_plural": "Daily Job Reports",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="JobMaterialReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artisan",
                    models.CharField(
                        choices=[
                            ("Mason", "Mason"),
                            ("Plumber", "Plumber"),
                            ("Electrician", "Electrician"),
                            ("Carpenter", "Carpenter"),
                            ("Painter", "Painter"),
                            ("Roofer", "Roofer"),
                            ("Iron Bender", "Iron Bender"),
                            ("Tiler", "Tiler"),
                            ("Glass Worker", "Glass Worker"),
                            ("Aluminium Worker", "Aluminium Worker"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "actual_quantity_used",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual quantity used on this day",
                        max_digits=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.material",
                    ),
                ),
                (
                    "job_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials_used",
                        to="core.jobreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Job Report Material",
                "verbose_name_plural": "Daily Job Report Materials",
            },
        ),
        migrations.DeleteModel(
            name="DailyReport",
        ),
        migrations.DeleteModel(
            name="DailyReportMaterial",
        ),
    ]
