# Generated by Django 6.0.4 on 2026-05-08 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_notification_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobreportcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.jobreportcomment'),
        ),
    ]
