# Generated by Django 6.0.4 on 2026-05-14 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_jobreportcomment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobreportcomment',
            name='parent',
        ),
        migrations.AddField(
            model_name='constructionplot',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='constructionplot',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='constructionplot',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='constructionplot',
            name='plot_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='material_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workitem',
            name='checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='JobReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reports/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.jobreport')),
            ],
        ),
        migrations.CreateModel(
            name='WorkItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_items/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.workitem')),
            ],
        ),
    ]
