# Generated by Django 6.0.4 on 2026-05-03 21:16

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_status', models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Delayed', 'Delayed'), ('Cancelled', 'Cancelled')], default='Planned', max_length=20)),
                ('job_artisan', models.CharField(choices=[('Mason', 'Mason'), ('Plumber', 'Plumber'), ('Electrician', 'Electrician'), ('Carpenter', 'Carpenter'), ('Painter', 'Painter'), ('Roofer', 'Roofer'), ('Iron Bender', 'Iron Bender'), ('Tiler', 'Tiler'), ('Glass Worker', 'Glass Worker'), ('Aluminium Worker', 'Aluminium Worker'), ('Other', 'Other')], max_length=20)),
                ('job_name', models.CharField(default='', max_length=50)),
                ('job_description', models.TextField(default='')),
                ('projected_start_date', models.DateField()),
                ('projected_end_date', models.DateField()),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_status', models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Delayed', 'Delayed'), ('Cancelled', 'Cancelled')], default='Planned', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('project_name', models.CharField(default='', max_length=100)),
                ('project_description', models.TextField(default='')),
                ('project_start_date', models.DateField(default=datetime.date(2026, 5, 3))),
                ('project_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_owner', to=settings.AUTH_USER_MODEL)),
                ('consultants', models.ManyToManyField(blank=True, related_name='project_consultants', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=255)),
                ('plot_opening_date', models.DateField(default=datetime.date(2026, 5, 3))),
                ('foreman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plot_foreman', to=settings.AUTH_USER_MODEL)),
                ('storekeeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plot_storekeeper', to=settings.AUTH_USER_MODEL)),
                ('construction_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.constructionproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_status', models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Submitted', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=10)),
                ('report_date', models.DateField(default=datetime.date(2026, 5, 3))),
                ('percentage_job_progress', models.PositiveSmallIntegerField()),
                ('expected_completion_date', models.DateField(help_text='When this phase of work is expected to be completed')),
                ('issues_encountered', models.TextField(blank=True, help_text='Describe any issues or obstacles encountered')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations')),
                ('internal_comments', models.TextField(blank=True, help_text='Internal comments for project team')),
                ('external_comments', models.TextField(blank=True, help_text='Comments visible to client and consultants')),
                ('job_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_report_pictures', to='base.picture')),
                ('job_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='core.jobitem')),
                ('job_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_report_videos', to='base.video')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Job Report',
                'verbose_name_plural': 'Daily Job Reports',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JobReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.jobreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.constructionproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlotInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('Foreman', 'Foreman'), ('Storekeeper', 'Storekeeper')], max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_plot_invitations', to=settings.AUTH_USER_MODEL)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_plot_invitations', to=settings.AUTH_USER_MODEL)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.constructionplot')),
            ],
            options={
                'verbose_name': 'Plot Invitation',
                'verbose_name_plural': 'Plot Invitations',
            },
        ),
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('Project Manager', 'Project Manager'), ('Client', 'Client'), ('Consultant', 'Consultant')], max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_project_invitations', to=settings.AUTH_USER_MODEL)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_project_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.constructionproject')),
            ],
            options={
                'verbose_name': 'Project Invitation',
                'verbose_name_plural': 'Project Invitations',
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_status', models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Delayed', 'Delayed'), ('Cancelled', 'Cancelled')], default='Planned', max_length=20)),
                ('name', models.CharField(default='', max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
                ('proposed_start_date', models.DateField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('proposed_end_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('construction_plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.constructionplot')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='jobitem',
            name='work_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_items', to='core.workitem'),
        ),
        migrations.AddConstraint(
            model_name='constructionproject',
            constraint=models.CheckConstraint(condition=models.Q(('project_end_date__gte', models.F('project_start_date')), ('project_end_date__isnull', True), _connector='OR'), name='end_date_after_start_date'),
        ),
        migrations.AddConstraint(
            model_name='constructionproject',
            constraint=models.UniqueConstraint(fields=('created_by', 'project_name'), name='unique_project_name'),
        ),
        migrations.AddConstraint(
            model_name='plotinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('plot', 'invitee', 'role'), name='unique_pending_plot_invitation'),
        ),
        migrations.AddConstraint(
            model_name='projectinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('project', 'invitee', 'role'), name='unique_pending_project_invitation'),
        ),
    ]
