# Generated by Django 6.0.4 on 2026-05-04 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionproject',
            name='number_of_plots',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='constructionplot',
            name='plot_opening_date',
            field=models.DateField(default=datetime.date(2026, 5, 4)),
        ),
        migrations.AlterField(
            model_name='constructionproject',
            name='project_start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='jobreport',
            name='report_date',
            field=models.DateField(default=datetime.date(2026, 5, 4)),
        ),
    ]
