# Generated by Django 6.0.4 on 2026-05-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_constructionproject_number_of_plots_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructionproject',
            old_name='project_end_date',
            new_name='actual_end_date',
        ),
        migrations.RenameField(
            model_name='constructionproject',
            old_name='project_start_date',
            new_name='proposed_start_date',
        ),
        migrations.AddField(
            model_name='constructionproject',
            name='proposed_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobreport',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Critical', 'Critical')], default='Normal', max_length=10),
        ),
    ]
