# Generated by Django 6.0.4 on 2026-05-04 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_project_end_date_constructionproject_actual_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='constructionproject',
            name='end_date_after_start_date',
        ),
        migrations.AddConstraint(
            model_name='constructionproject',
            constraint=models.CheckConstraint(condition=models.Q(('proposed_end_date__gte', models.F('proposed_start_date')), ('proposed_end_date__isnull', True), _connector='OR'), name='proposed_end_date_after_proposed_start_date'),
        ),
        migrations.AddConstraint(
            model_name='constructionproject',
            constraint=models.CheckConstraint(condition=models.Q(('actual_end_date__gte', models.F('actual_start_date')), ('actual_end_date__isnull', True), _connector='OR'), name='actual_end_date_after_actual_start_date'),
        ),
    ]
