# Generated by Django 6.0.4 on 2026-05-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_constructionproject_end_date_after_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionproject',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
