# Generated by Django 6.0.4 on 2026-05-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_constructionproject_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionproject',
            name='address',
        ),
    ]
