# Generated by Django 6.0.4 on 2026-05-06 06:35

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_constructionproject_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobitem',
            old_name='work_status',
            new_name='job_status',
        ),
        migrations.AlterField(
            model_name='constructionplot',
            name='plot_opening_date',
            field=models.DateField(default=datetime.date(2026, 5, 6)),
        ),
        migrations.AlterField(
            model_name='jobreport',
            name='report_date',
            field=models.DateField(default=datetime.date(2026, 5, 6)),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='proposed_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
