# Generated by Django 6.0.4 on 2026-05-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_work_status_jobitem_job_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='proposed_start_date',
            field=models.DateField(),
        ),
    ]
