# Generated by Django 6.0.4 on 2026-05-08 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_workitem_proposed_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvitation',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='constructionplot',
            name='plot_opening_date',
            field=models.DateField(default=datetime.date(2026, 5, 8)),
        ),
        migrations.AlterField(
            model_name='jobreport',
            name='report_date',
            field=models.DateField(default=datetime.date(2026, 5, 8)),
        ),
    ]
