# Generated by Django 6.0.4 on 2026-05-08 05:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_projectinvitation_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionplot',
            name='plot_opening_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobreport',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
