# Generated by Django 6.0.4 on 2026-05-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_constructionplot_plot_opening_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotinvitation',
            name='role',
            field=models.CharField(choices=[('foreman', 'Foreman'), ('storekeeper', 'Storekeeper')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projectinvitation',
            name='role',
            field=models.CharField(choices=[('project_manager', 'Project Manager'), ('client', 'Client'), ('consultant', 'Consultant')], max_length=20),
        ),
    ]
