# Generated by Django 6.0.4 on 2026-05-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_plot_extras_workitem_checklist_jobitem_materials_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
