# Generated by Django 6.0.4 on 2026-05-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_jobreportcomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
