# Generated by Django 6.0.4 on 2026-05-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_jobitem_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=20),
        ),
    ]
