# Generated by Django 6.0.4 on 2026-05-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_jobitem_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionplot',
            name='status',
            field=models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Delayed', 'Delayed'), ('Cancelled', 'Cancelled')], default='Planned', max_length=20),
        ),
    ]
