# Generated by Django 6.0.4 on 2026-05-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobitembudget',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AlterField(
            model_name='plotbudget',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AlterField(
            model_name='projectbudget',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AlterField(
            model_name='workitembudget',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
    ]
