"""
Django settings for site_base project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/topics/settings/
"""

import configparser
from datetime import timedelta
import os
from pathlib import Path
# import cloudinary
# import cloudinary.uploader

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent.parent

APP_DIR = os.path.join(BASE_DIR, "apps")

CFG = configparser.ConfigParser()

if os.path.exists(os.path.join(BASE_DIR, "envs", "dev.env")):
    CFG.read(os.path.join(BASE_DIR, "envs", "dev.env"))
    DEBUG = True
else:
    CFG.read(os.path.join(BASE_DIR, "env", "prod.env"))
    DEBUG = False


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "bfquhufqhhfiqfhhqubefiwcn87824329yr928mc3q9&T%TDMG" #config("SECRET_KEY", default='')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True # config("DEBUG", default=True)

# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    # "cloudinary_storage",
    "django.contrib.staticfiles",
    "django.contrib.sites",
]

CUSTOM_USER_APPS  = [
    "accounts",
    "base",
    "core",
    "finance",
]

THIRD_PARTY_APPS = [
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "django_browser_reload",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.apple",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    # "cloudinary",
]

INSTALLED_APPS = DJANGO_APPS + CUSTOM_USER_APPS + THIRD_PARTY_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

X_FRAME_OPTIONS = "ALLOW-FROM preview.app.github.dev"

ROOT_URLCONF = "site_base.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "site_base" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "site_base.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATICFILES_DIRS = [
    BASE_DIR / "site_base" / "static",
]

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "site_base" / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "site_base" / "media"

# CLOUDINARY_STORAGE = {
#     'CLOUD_NAME': CFG.get('CLOUDINARY', 'CLOUDINARY_CLOUD_NAME', fallback=''),
#     'API_KEY': CFG.get('CLOUDINARY', 'CLOUDINARY_API_KEY', fallback=''),
#     'API_SECRET': CFG.get('CLOUDINARY', 'CLOUDINARY_API_SECRET', fallback=''),
# }

# Explicitly configure the Cloudinary SDK so URL generation and uploads work
# without relying solely on cloudinary_storage's lazy initialization.
# cloudinary.config(
#     cloud_name=CLOUDINARY_STORAGE['CLOUD_NAME'],
#     api_key=CLOUDINARY_STORAGE['API_KEY'],
#     api_secret=CLOUDINARY_STORAGE['API_SECRET'],
#     secure=True,  # Always use https:// URLs
# )

# STORAGES = {
#     "default": {
#         "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
#     },
#     "staticfiles": {
#         "BACKEND": "cloudinary_storage.storage.StaticHashedCloudinaryStorage",
#     },
# }


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = 'accounts.UserModel'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Simple JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'SIGNING_KEY': CFG.get("SITE", "DJANGO_SECRET_KEY",)
}

# dj-rest-auth JWT configuration
REST_AUTH = {
    'USE_JWT': True,
    'TOKEN_MODEL': None,           # Disable DRF authtoken — we use JWT
    'JWT_AUTH_COOKIE': None,       # Stateless — tokens in Authorization header
    'JWT_AUTH_REFRESH_COOKIE': None,
    'JWT_AUTH_HTTPONLY': False,
    'SESSION_LOGIN': False,
}

# django-allauth & dj-rest-auth Configuration
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

ACCOUNT_UNIQUE_EMAIL = True
# Allow login with both email and username
ACCOUNT_LOGIN_METHODS = {'email', 'username'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'   # Custom email confirmation handled in RegisterView
SOCIALACCOUNT_QUERY_EMAIL = True

